name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u ab1997 -p j@griti15
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Docker/PortableLinuxBinaries_aarch64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ab1997/portable-linux-binaries:latest-arm64
